import React, { createContext, useContext, useState } from 'react';

type Language = 'ta' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ta: {
    // Login & Auth
    'login': 'உள்நுழைவு',
    'signin': 'உள்நுழையவும்',
    'welcome': 'வரவேற்கிறோம்!',
    'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
    'signin_account': 'உங்கள் NAAM கணக்கில் உள்நுழையவும்',
    'enter_credentials': 'உங்கள் விவரங்களை உள்ளிடுங்கள்',
    'mobile_otp': 'மொபைல் OTP',
    'otp': 'OTP',
    'enter_mobile': 'மொபைல் எண்ணை உள்ளிடுங்கள்',
    'send_otp': 'OTP அனுப்பவும்',
    'enter_otp': 'OTP ஐ உள்ளிடுங்கள்',
    'enter_6_digit_otp': '6 இலக்க OTP ஐ உள்ளிடுங்கள்',
    'verify_login': 'சரிபார்த்து உள்நுழையவும்',
    'resend_otp': 'OTP ஐ மீண்டும் அனுப்பு',
    'invalid_mobile': 'தவறான மொபைல் எண்',
    'invalid_otp': 'தவறான OTP',
    'login_successful': 'வெற்றிகரமாக உள்நுழைந்தீர்கள்',
    'error': 'பிழை',
    'enter_mobile_error': 'தயவுசெய்து உங்கள் தொலைபேசி எண்ணை உள்ளிடுங்கள்',
    'enter_otp_error': 'தயவுசெய்து OTP ஐ உள்ளிடுங்கள்',
    'otp_sent': 'OTP அனுப்பப்பட்டது',
    'check_mobile_otp': 'OTP க்காக உங்கள் மொபைலை சரிபார்க்கவும்',
    'no_account': 'கணக்கு இல்லையா? ',
    
    // Placeholders
    'enter_full_name': 'உங்கள் முழு பெயரை உள்ளிடுங்கள்',
    'enter_mobile_number': 'மொபைல் எண்ணை உள்ளிடுங்கள்',
    'enter_email': 'மின்னஞ்சல் முகவரியை உள்ளிடுங்கள்',
    'enter_address': 'உங்கள் முகவரியை உள்ளிடுங்கள்',
    'enter_pincode': 'பின்கோட்டை உள்ளிடுங்கள்',
    'enter_coordinates': 'ஆயத்தொலைவுகளை உள்ளிடுங்கள்',
    'enter_patta_number': 'பட்டா எண்ணை உள்ளிடுங்கள்',
    'enter_account_holder_name': 'கணக்கு வைத்திருப்பவர் பெயரை உள்ளிடுங்கள்',
    'enter_bank_name': 'வங்கி பெயரை உள்ளிடுங்கள்',
    'enter_branch_name': 'கிளை பெயரை உள்ளிடுங்கள்',
    'enter_ifsc_code': 'IFSC குறியீட்டை உள்ளிடுங்கள்',
    'enter_account_number': 'கணக்கு எண்ணை உள்ளிடுங்கள்',
    'enter_upi_id': 'UPI ஐடியை உள்ளிடுங்கள்',
    'join_naam': 'NAAM இல் சேரவும்',
    'join_farmer': 'Join AS Farmer',
    'choose_role': 'தொடங்க உங்கள் பாத்திரத்தை தேர்வு செய்யுங்கள்',
    'new_registration': 'புதிய பதிவு',
    'preferred_language': 'விருப்ப மொழி',
    'choose_location_title': 'இருப்பிடம் தேர்ந்தெடுக்கவும்',
    'pin_code': 'பின் கோடு',
    'my_location': 'எனது இருப்பிடம்',
    'manual_selection': 'கைமுறை தேர்வு',
    'continue': 'தொடரவும்',
    'farmer': 'விவசாயி',
    'investor': 'முதலீட்டாளர்',
    'service_provider': 'சேவை வழங்குநர்',
    'nam_member': 'NAAM உறுப்பினர்',
    'farmer_desc': 'உங்கள் விளைபொருட்களை வளர்த்து விற்கவும்',
    'investor_desc': 'விவசாய திட்டங்களில் முதலீடு செய்யுங்கள்',
    'service_desc': 'விவசாய சேவைகளை வழங்குங்கள்',
    'nam_desc': 'NAAM அமைப்பு உறுப்பினர்',
    'registration_fee': 'பதிவு கட்டணம்: ₹',
    'english': 'English',
    'farmer_registration': 'விவசாயி பதிவு',
    'complete_registration': 'உங்கள் பதிவை முடிக்கவும்',
    'basic_info': 'அடிப்படை தகவல்',
    'land_details': 'நில விவரங்கள்',
    'documents': 'ஆவணங்கள்',
    'bank_info': 'வங்கி தகவல்',
    'previous': 'முந்தைய',
    'next': 'அடுத்து',
    'submit_registration': 'பதிவை சமர்பிக்கவும்',
    'registration_successful': 'பதிவு வெற்றிகரமாக முடிந்தது!',
    'full_name': 'முழு பெயர்',
    'mobile_number': 'தொலைபேசி எண்',
    'alternate_mobile': 'மாற்று தொலைபேசி எண்',
    'email_id': 'மின்னஞ்சல் முகவரி',
    'address': 'முகவரி',
    'state': 'மாநிலம்',
    'district': 'மாவட்டம்',
    'taluk_block': 'தாலுக் / பிளாக்',
    'village_panchayat': 'கிராமம் / பஞ்சாயத்து',
    'pincode': 'பின்கோட்',
    'gender': 'பாலினம்',
    'male': 'ஆண்',
    'female': 'பெண்',
    'date_of_birth': 'பிறந்த தேதி',
    'age': 'வயது',
    'land_ownership_type': 'நில உரிமை வகை',
    'total_land_holding': 'மொத்த நில வைத்திருப்பு (ஏக்கரில்)',
    'irrigation_source': 'நீர்ப்பாசன மூலம்',
    'soil_type': 'மண் வகை',
    'irrigation_type': 'நீர்ப்பாசன வகை',
    'location_coordinates': 'இடம் (அட்சரேகை, தீர்க்கரேகை)',
    'geo_tagged_photo': 'புவி குறியிடப்பட்ட பண்ணை புகைப்படம்',
    'patta_no': 'பட்டா எண்',
    'coconut_farming': 'தென்னை விவசாயம்',
    'yes': 'ஆம்',
    'no': 'இல்லை',
    'coconut_area': 'தென்னை சாகுபடி பகுதி (ஏக்கரில்)',
    'number_of_trees': 'தென்னை மரங்களின் எண்ணிக்கை',
    'average_age_trees': 'மரங்களின் சராசரி வயது',
    'estimated_coconuts': 'இரண்டு மாதங்களுக்கு ஒருமுறை விழும் தேங்காய்களின் எண்ணிக்கை',
    'last_harvest_date': 'கடைசி அறுவடை தேதி',
    'aadhar_card': 'ஆதார் அட்டை நகல்',
    'pan_card': 'பான் அட்டை நகல்',
    'passport_photo': 'சமீபத்திய பாஸ்போர்ட் அளவு புகைப்படம்',
    'account_holder_name': 'கணக்கு வைத்திருப்பவர் பெயர்',
    'bank_name': 'வங்கி பெயர்',
    'branch_name': 'கிளை பெயர்',
    'ifsc_code': 'IFSC குறியீடு',
    'account_number': 'கணக்கு எண்',
    'account_type': 'கணக்கு வகை',
    'bank_passbook': 'வங்கி பாஸ்புக் நகல்',
    'bank_passbook_copy': 'வங்கி பாஸ்புக் நகல்',
    'upi_id': 'UPI ஐடி',
    'enter_upi_id_optional': 'UPI ஐடி உள்ளிடுங்கள் (விருப்பம்)',
    'take_photo': 'புகைப்படம் எடுக்கவும்',
    'choose_photo': 'புகைப்படம் தேர்வு செய்யுங்கள்',
    'uploaded': 'பதிவேற்றப்பட்டது',
    'owned': 'சொந்தமான',
    'leased': 'குத்தகை',
    'joint_ownership': 'கூட்டு உரிமை',
    'borewell': 'போர்வெல்',
    'canal': 'கால்வாய்',
    'drip': 'சொட்டு நீர்',
    'manual': 'கைமுறை',
    'sandy': 'மணல்',
    'loamy': 'களிமண்',
    'clayey': 'களிமண்',
    'laterite': 'லேட்டரைட்',
    'savings': 'சேமிப்பு',
    'current': 'நடப்பு',
    'welcome_naam': 'NAAM',
    'select_state': 'மாநிலத்தை தேர்வு செய்யவும்',
    'select_district': 'மாவட்டத்தை தேர்வு செய்யுங்கள்',
    'select_taluk': 'தாலுக்கை தேர்வு செய்யுங்கள்',
    'select_village': 'கிராமத்தை தேர்வு செய்யுங்கள்',
    'select_ownership': 'உரிமை வகையை தேர்வு செய்யுங்கள்',
    'select_irrigation_source': 'நீர்ப்பாசன மூலத்தை தேர்வு செய்யுங்கள்',
    'select_soil_type': 'மண் வகையை தேர்வு செய்யுங்கள்',
    'select_irrigation_type': 'நீர்ப்பாசன வகையை தேர்வு செய்யுங்கள்',
    'select_account_type': 'கணக்கு வகையை தேர்வு செய்யுங்கள்',
    'select_dob': 'பிறந்த தேதியை தேர்வு செய்யுங்கள்',
    'select_harvest_date': 'கடைசி அறுவடை தேதியை தேர்வு செய்யுங்கள்',
    'basic_information': 'அடிப்படை தகவல்கள்',
    'coconut_farming_details': 'தென்னை விவசாய விவரங்கள்',
    'bank_details': 'வங்கி விவரங்கள்',
    'age_calculated': 'வயது கணக்கிடப்பட்டது',
    'enter_total_land': 'மொத்த நில வைத்திருப்பை உள்ளிடுங்கள்',
    'enter_area_acres': 'பகுதியை ஏக்கரில் உள்ளிடுங்கள்',
    'enter_number_trees': 'மரங்களின் எண்ணிக்கையை உள்ளிடுங்கள்',
    'enter_average_age': 'சராசரி வயதை வருடங்களில் உள்ளிடுங்கள்',
    'enter_estimated_number': 'மதிப்பிடப்பட்ட எண்ணிக்கையை உள்ளிடுங்கள்',
    'select_state_first': 'முதலில் மாநிலத்தை தேர்வு செய்யவும்',
    'select_district_first': 'முதலில் மாவட்டத்தை தேர்வு செய்யவும்',
    'select_taluk_first': 'முதலில் தாலுக்கை தேர்வு செய்யவும்',
    'select_land_state_first': 'முதலில் நில மாநிலத்தை தேர்வு செய்யவும்',
    'select_land_district_first': 'முதலில் நில மாவட்டத்தை தேர்வு செய்யவும்',
    'select_land_taluk_first': 'முதலில் நில தாலுக்கை தேர்வு செய்யவும்',
    'farm_photo_uploaded': 'பண்ணை புகைப்படம் பதிவேற்றப்பட்டது',
    'aadhar_uploaded': 'ஆதார் அட்டை பதிவேற்றப்பட்டது',
    'pan_uploaded': 'பான் அட்டை பதிவேற்றப்பட்டது',
    'passport_uploaded': 'பாஸ்போர்ட் புகைப்படம் பதிவேற்றப்பட்டது',
    'passbook_uploaded': 'வங்கி பாஸ்புக் பதிவேற்றப்பட்டது',

    'enter_patta_no': 'பட்டா எண்ணை உள்ளிடுங்கள் (விருப்பம்)',
    'select_land_state': 'நில மாநிலத்தை தேர்வு செய்யவும்',
    'select_land_district': 'நில மாவட்டத்தை தேர்வு செய்யவும்',
    'select_land_taluk': 'நில தாலுக்கை தேர்வு செய்யவும்',
    'select_land_village': 'நில கிராமத்தை தேர்வு செய்யவும்',
    'search_select_location': 'இடத்தை தேடி தேர்வு செய்யவும்',
    'confirm_location': 'இடத்தை உறுதி செய்யவும்',
    'cancel': 'ரத்து செய்யவும்',
    'confirm': 'உறுதி செய்யவும்',
    'investor_registration': 'முதலீட்டாளர் பதிவு',
    'land_details_optional': 'நில விவரங்கள் (வேண்டுமென்றால்)',
    'enter_age': 'வயதை உள்ளிடுங்கள்',
    'select_land_state_title': 'நில மாநிலத்தை தேர்வு செய்யவும்',
    'select_land_district_title': 'நில மாவட்டத்தை தேர்வு செய்யவும்',
    'select_land_taluk_title': 'நில தாலுக்கை தேர்வு செய்யவும்',
    'select_land_village_title': 'நில கிராமத்தை தேர்வு செய்யவும்',
    'service_provider_registration': 'சேவை வழங்குநர் பதிவு',
    'services': 'சேவைகள்',
    'services_offered': 'வழங்கும் சேவைகள்',
    'category': 'வகை',
    'subcategory': 'உபவகை',
    'select_service_category': 'சேவை வகையை தேர்வு செய்யவும்',
    'select_subcategory': 'உபவகையை தேர்வு செய்யவும்',
    'select_category_first': 'முதலில் வகையை தேர்வு செய்யவும்',
    'nam_member_registration': 'NAAM உறுப்பினர் பதிவு',
    'payment_required': 'கட்டணம் தேவை',
    'dashboard': 'கண்ணோட்டம்',
    'welcome_dashboard': 'முதன்மை பக்கம்',
    'manage_account': 'உங்கள் கணக்கை நிர்வகிக்கவும்',
    'total_yield': 'மொத்த விளைச்சல்',
    'payments': 'பணம்',
    'services_completed': 'முடிக்கப்பட்ட சேவைகள்',
    'total_earnings': 'மொத்த வருமானம்',
    'profile': 'சுயவிவரம்',
    'reports': 'அறிக்கைகள்',
    'settings': 'அமைப்புகள்',
    'coconuts_procured': 'விற்கப்பட்ட தேங்காய்கள்',
    'payment_spending': 'நிலுவைத் தொகை',
    'pending_payment': 'நிலுவைத் தொகை',
    'home': 'முகப்பு',
    'validate_account': 'கணக்கை சரிபார்க்கவும்',
    'validating': 'சரிபார்க்கிறது...',
    'account_validated_successfully': 'கணக்கு வெற்றிகரமாக சரிபார்க்கப்பட்டது',
    'logout': 'வெளியேறு',
    'language': 'மொழி',
    'manage_preferences': 'உங்கள் விருப்பங்களை நிர்வகிக்கவும்',
    'coconut_collections': 'விற்கப்பட்ட தேங்காய்கள்',
    'pending_payments': 'நிலுவைத் தொகைகள்',
    'detailed_view': 'விரிவான காட்சி',
    'date': 'தேதி',
    'count': 'எண்ணிக்கை',
    'price_per_coconut': 'தேங்காய் விலை',
    'total_cost': 'மொத்த செலவு',
    'quality': 'தரம்',
    'amount': 'தொகை',
    'mobile': 'மொபைல்',
    'no_data_available': 'தரவு இல்லை',
    'loading': 'ஏற்றுகிறது...',
    'good': 'நல்லது',
    'pending': 'நிலுவையில்',
    'paid': 'செலுத்தப்பட்டது',
    'year': 'ஆண்டு',
    'farmer_name': 'விவசாயி பெயர்'
  },
  en: {
    // Login & Auth
    'login': 'Login',
    'signin': 'Sign In',
    'welcome': 'Welcome!',
    'welcome_back': 'Welcome Back',
    'signin_account': 'Sign in to your NAAM account',
    'enter_credentials': 'Enter your credentials',
    'mobile_otp': 'Mobile OTP',
    'otp': 'OTP',
    'enter_mobile': 'Enter mobile number',
    'send_otp': 'Send OTP',
    'enter_otp': 'Enter OTP',
    'enter_6_digit_otp': 'Enter 6-digit OTP',
    'verify_login': 'Verify & Login',
    'resend_otp': 'Resend OTP',
    'invalid_mobile': 'Invalid mobile number',
    'invalid_otp': 'Invalid OTP',
    'login_successful': 'Login successful',
    'error': 'Error',
    'enter_mobile_error': 'Please enter your mobile number',
    'enter_otp_error': 'Please enter the OTP',
    'otp_sent': 'OTP Sent',
    'check_mobile_otp': 'Please check your mobile for the OTP',
    'no_account': "Don't have an account? ",
    
    // Placeholders
    'enter_full_name': 'Enter your full name',
    'enter_mobile_number': 'Enter mobile number',
    'enter_email': 'Enter email address',
    'enter_address': 'Enter your address',
    'enter_pincode': 'Enter pincode',
    'enter_coordinates': 'Enter coordinates',
    'enter_patta_number': 'Enter Patta number',
    'enter_account_holder_name': 'Enter account holder name',
    'enter_bank_name': 'Enter bank name',
    'enter_branch_name': 'Enter branch name',
    'enter_ifsc_code': 'Enter IFSC code',
    'enter_account_number': 'Enter account number',
    'enter_upi_id': 'Enter UPI ID (optional)',
    'join_naam': 'Join NAAM',
    'join_farmer': 'Join AS Farmer',
    'choose_role': 'Choose your role to get started',
    'new_registration': 'New Registration',
    'preferred_language': 'Preferred Language',
    'choose_location_title': 'Choose location',
    'pin_code': 'Pin code',
    'my_location': 'My location',
    'manual_selection': 'Choose manually',
    'continue': 'Continue',
    'farmer': 'Farmer',
    'investor': 'Investor',
    'service_provider': 'Service Provider',
    'nam_member': 'NAAM Member',
    'farmer_desc': 'Grow and sell your produce',
    'investor_desc': 'Invest in agricultural projects',
    'service_desc': 'Provide agricultural services',
    'nam_desc': 'NAM organization member',
    'registration_fee': 'Registration Fee: ₹',
    'english': 'English',
    'farmer_registration': 'Farmer Registration',
    'complete_registration': 'Complete your registration',
    'basic_info': 'Basic Info',
    'land_details': 'Land Details',
    'documents': 'Documents',
    'bank_info': 'Bank Info',
    'previous': 'Previous',
    'next': 'Next',
    'submit_registration': 'Submit Registration',
    'registration_successful': 'Registration Successful!',
    'full_name': 'Full Name',
    'mobile_number': 'Mobile Number',
    'alternate_mobile': 'Alternate Mobile Number',
    'email_id': 'Email ID',
    'address': 'Address',
    'state': 'State',
    'district': 'District',
    'taluk_block': 'Taluk / Block',
    'village_panchayat': 'Village / Panchayat',
    'pincode': 'Pincode',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'date_of_birth': 'Date of Birth',
    'age': 'Age',
    'land_ownership_type': 'Land Ownership Type',
    'total_land_holding': 'Total Land Holding (in acres)',
    'irrigation_source': 'Irrigation Source',
    'soil_type': 'Soil Type',
    'irrigation_type': 'Irrigation Type',
    'location_coordinates': 'Location (Latitude, Longitude)',
    'geo_tagged_photo': 'Geo-tagged Farm Photo',
    'patta_no': 'Patta No',
    'coconut_farming': 'Coconut Farming',
    'yes': 'Yes',
    'no': 'No',
    'coconut_area': 'Area Under Coconut Cultivation (in acres)',
    'number_of_trees': 'Number of Coconut Trees',
    'average_age_trees': 'Average Age of Trees',
    'estimated_coconuts': 'Estimated Coconuts Falling Every Two Months',
    'last_harvest_date': 'Last Harvest Date',
    'aadhar_card': 'Aadhaar Card Copy',
    'pan_card': 'PAN Copy',
    'passport_photo': 'Recent Passport-size Photo',
    'account_holder_name': 'Account Holder Name',
    'bank_name': 'Bank Name',
    'branch_name': 'Branch Name',
    'ifsc_code': 'IFSC Code',
    'account_number': 'Account Number',
    'account_type': 'Account Type',
    'bank_passbook': 'Bank Passbook Copy',
    'bank_passbook_copy': 'Bank Passbook Copy',
    'upi_id': 'UPI ID',
    'enter_upi_id_optional': 'Enter UPI ID (optional)',
    'enter_patta_no': 'Enter Patta No (optional)',
    'take_photo': 'Take Photo',
    'choose_photo': 'Choose Photo',
    'uploaded': 'uploaded',
    'owned': 'Owned',
    'leased': 'Leased',
    'joint_ownership': 'Joint ownership',
    'borewell': 'Borewell',
    'canal': 'Canal',
    'drip': 'Drip',
    'manual': 'Manual',
    'sandy': 'Sandy',
    'loamy': 'Loamy',
    'clayey': 'Clayey',
    'laterite': 'Laterite',
    'savings': 'Savings',
    'current': 'Current',
    'welcome_naam': 'Welcome to NAAM!',
    'select_state': 'Select State',
    'select_district': 'Select District',
    'select_taluk': 'Select Taluk',
    'select_village': 'Select Village',
    'select_ownership': 'Select Ownership Type',
    'select_irrigation_source': 'Select Irrigation Source',
    'select_soil_type': 'Select Soil Type',
    'select_irrigation_type': 'Select Irrigation Type',
    'select_account_type': 'Select Account Type',
    'select_dob': 'Select Date of Birth',
    'select_harvest_date': 'Select Last Harvest Date',
    'basic_information': 'Basic Information',
    'coconut_farming_details': 'Coconut Farming Details',
    'bank_details': 'Bank Details',
    'age_calculated': 'Age calculated automatically',
    'enter_total_land': 'Enter total land holding',
    'enter_area_acres': 'Enter area in acres',
    'enter_number_trees': 'Enter number of trees',
    'enter_average_age': 'Enter average age in years',
    'enter_estimated_number': 'Enter estimated number',
    'select_state_first': 'Please select state first',
    'select_district_first': 'Please select district first',
    'select_taluk_first': 'Please select taluk first',
    'select_land_state_first': 'Please select land state first',
    'select_land_district_first': 'Please select land district first',
    'select_land_taluk_first': 'Please select land taluk first',
    'farm_photo_uploaded': 'Farm photo uploaded',
    'aadhar_uploaded': 'Aadhaar card uploaded',
    'pan_uploaded': 'PAN card uploaded',
    'passport_uploaded': 'Passport photo uploaded',
    'passbook_uploaded': 'Bank passbook uploaded',
    'select_land_state': 'Select Land State',
    'select_land_district': 'Select Land District',
    'select_land_taluk': 'Select Land Taluk',
    'select_land_village': 'Select Land Village',
    'search_select_location': 'Search and select location',
    'confirm_location': 'Confirm Location',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'investor_registration': 'Investor Registration',
    'land_details_optional': 'Land Details (Optional)',
    'enter_age': 'Enter age',
    'select_land_state_title': 'Select Land State',
    'select_land_district_title': 'Select Land District',
    'select_land_taluk_title': 'Select Land Taluk',
    'select_land_village_title': 'Select Land Village',
    'service_provider_registration': 'Service Provider Registration',
    'services': 'Services',
    'services_offered': 'Services Offered',
    'category': 'Category',
    'subcategory': 'Subcategory',
    'select_service_category': 'Select Service Category',
    'select_subcategory': 'Select Subcategory',
    'select_category_first': 'Please select category first',
    'nam_member_registration': 'NAAM Member Registration',
    'payment_required': 'Payment Required',
    'dashboard': 'Dashboard',
    'welcome_dashboard': 'Welcome to Dashboard',
    'manage_account': 'Manage your account',
    'total_yield': 'Total Yield',
    'payments': 'Payments',
    'services_completed': 'Services Completed',
    'total_earnings': 'Total Earnings',
    'profile': 'Profile',
    'reports': 'Reports',
    'settings': 'Settings',
    'coconuts_procured': 'Coconuts Procured',
    'payment_spending': 'Payment Spending',
    'pending_payment': 'Pending Payment',
    'home': 'Home',
    'validate_account': 'Validate Account',
    'validating': 'Validating...',
    'account_validated_successfully': 'Account validated successfully',
    'logout': 'Logout',
    'language': 'Language',
    'manage_preferences': 'Manage your preferences',
    'coconut_collections': 'Coconut Collections',
    'pending_payments': 'Pending Payments',
    'detailed_view': 'Detailed View',
    'date': 'Date',
    'count': 'Count',
    'price_per_coconut': 'Price/Coconut',
    'total_cost': 'Total Cost',
    'quality': 'Quality',
    'amount': 'Amount',
    'mobile': 'Mobile',
    'no_data_available': 'No data available',
    'loading': 'Loading...',
    'good': 'Good',
    'pending': 'Pending',
    'paid': 'Paid',
    'year': 'Year',
    'farmer_name': 'Farmer Name'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ta');

  const t = (key: string): string => {
    const dict = translations[language] as Record<string, string>;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};