#!/bin/bash
# Fix for React Native codegen missing files issue
# This ensures the codegen directory exists before build

mkdir -p build/generated/ios/react/renderer/components/rngesturehandler_codegen

# Create placeholder files if they don't exist (will be overwritten by actual codegen)
if [ ! -f "build/generated/ios/react/renderer/components/rngesturehandler_codegen/ComponentDescriptors.cpp" ]; then
    cat > "build/generated/ios/react/renderer/components/rngesturehandler_codegen/ComponentDescriptors.cpp" << 'EOF'
// Placeholder file - will be generated by React Native codegen
// This file is auto-generated and should not be edited manually
EOF
fi

echo "Codegen directory structure created"
